# Generated by Django 6.1 on 2026-08-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderline',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
