# Generated by Django 6.1 on 2026-08-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0005_remove_order_status_orderline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
