# Generated by Django 6.1 on 2026-08-18 11:49

import autoservice.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0009_remove_orderline_client_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=autoservice.models.default_due_date),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2026, 8, 18)),
        ),
    ]
