# Generated by Django 6.1 on 2026-08-18 12:18

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0010_order_due_date_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=tinymce.models.HTMLField(default='', max_length=500, verbose_name='Description'),
        ),
    ]
