# Generated by Django 6.1 on 2026-08-18 12:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0011_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=tinymce.models.HTMLField(default='', max_length=500, verbose_name='description'),
        ),
    ]
