# Generated by Django 6.1 on 2026-08-20 07:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0014_alter_carreview_car_alter_carreview_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carreview',
            options={'ordering': ['-date_created'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='ordernotes',
            options={'ordering': ['-date_created'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='carreview',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='ordernotes',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='carreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='ordernotes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='carreview',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='autoservice.car', verbose_name='Car'),
        ),
        migrations.AlterField(
            model_name='carreview',
            name='content',
            field=models.TextField(max_length=500, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2026, 8, 20)),
        ),
        migrations.AlterField(
            model_name='ordernotes',
            name='content',
            field=models.TextField(max_length=500, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='ordernotes',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='autoservice.order', verbose_name='Order'),
        ),
    ]
