# Generated by Django 6.1 on 2026-08-20 08:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0015_alter_carreview_options_alter_ordernotes_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernotes',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordernotes',
            name='user',
        ),
        migrations.CreateModel(
            name='CarComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('content', models.TextField(max_length=500, verbose_name='Car comments')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='autoservice.car', verbose_name='Car')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Car comment',
                'verbose_name_plural': 'Car comments',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('content', models.TextField(max_length=500, verbose_name='Order comments')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='autoservice.order', verbose_name='Order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order comment',
                'verbose_name_plural': 'Order comments',
                'ordering': ['-date_created'],
            },
        ),
        migrations.DeleteModel(
            name='CarReview',
        ),
        migrations.DeleteModel(
            name='OrderNotes',
        ),
    ]
